# (Required.) Project name. Should be alpha-numeric, spaces are allowed.
name: Spark Example

# (Required.) Drupal 8 is currently the only platform Spark supports.
# This is probably getting deprecated as soon as we introduce the option to define services for your
# project.
platform: drupal8

# (Optional.) Automated testing command options.
test:
  init:
    - /var/www/html/scripts/behat.sh
  exec:
    - /opt/drupalextension/bin/behat --config /var/www/html/behat/behat.spark.yml

# (Optional.) Configuration for database exports.
database-export:

  # (Optional.) Data sanitization rules.
  sanitization:

    # (Optional.) Language in which Faker should generate fake data. Default: en_US.
    # See available languages here:
    # https://github.com/fzaninotto/Faker/tree/master/src/Faker/Provider.
    faker-locale: fr_FR
    # (Required.) Sanitization rules.
    rules:
      # Database tables.
      users_field_data:
        # Database columns and Faker formatters. See the list of formatters here:
        # https://github.com/fzaninotto/Faker#formatters
        # Please note that not all formatters are available on all languages for Faker. Make sure to
        # use formatters that are available with the selected Faker locale. See the formatters in
        # the folders here: https://github.com/fzaninotto/Faker/tree/master/src/Faker/Provider.
        name: userName
        mail: email

  # (Optional.) List of tables to discard data from. Only their structure will be exported.
  no-data:
    - batch
    - cache
    - /cache_.*/ # Notice how regular expressions can be used.
    - flood
    - persistent_login
    - queue
    - semaphore
    - sessions
    - watchdog

  # (Optional.) List of tables to completely skip from the export.
  exclude-tables:
    - table1
    - table2
