version: '2.1'

services:

  php:
    image: wodby/php:7.1-3.0.0
    environment:
      PHP_FPM_CLEAR_ENV: "no"
      DB_HOST: db
      DB_USER: spark
      DB_PASSWORD: spark
      DB_NAME: spark
      DB_DRIVER: mysql
      COMPOSER_ALLOW_SUPERUSER: 1
    volumes:
      - "./:/var/www/html"

  nginx:
    image: wodby/drupal-nginx:7-1.13-3.0.1
    depends_on:
      - php
    environment:
      NGINX_SERVER_NAME: localhost
      NGINX_STATIC_CONTENT_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html/www
    volumes:
      - "./:/var/www/html"
    ports:
      - "7500:80"

  db:
    image: wodby/mariadb:10.1-2.3.5
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: spark
      MYSQL_USER: spark
      MYSQL_PASSWORD: spark
    healthcheck:
      test: "mysqladmin -uroot -proot ping --silent"
    ports:
      - "7501:3306"
