# For a full reference, please see the `.spark.example.yml` file in the repository's root.

name: Spark D8 Example
platform: drupal8

command:
  drupal:
    backup:
      options:
        keep: 15 days
        bucket: bsp-spark-d8-example
        region: us-east-1
        truncate: cache,cache_*,sessions,watchdog
        files:
          - web/sites/default/files
          - private
        exclude:
          - css
          - js
          - styles
          - php
